import "./globals.css";

import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	metadataBase: new URL(
		process.env.NEXT_PUBLIC_WEBSITE_URL ||
			"https://azuretranslatorcode.vercel.app",
	),

	title: "Azure Translator Code",
	description: "Generated by Azure Translator Code",
	authors: { name: "Gabriel Logan" },
	classification: "translator",
	generator: "Next.js",
	publisher: "Gabriel Logan",
	creator: "Gabriel Logan",

	openGraph: {
		title: "Azure Translator Code",
		description: "Generated by Azure Translator Code",
		url: process.env.NEXT_PUBLIC_WEBSITE_URL,
		siteName: "Azure Translator Code",
		type: "website",
	},

	keywords: ["translator", "code", "azure", "microsoft"],

	manifest: "/manifest.webmanifest",

	category: "translator",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				<Analytics />
			</body>
		</html>
	);
}
