import { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
	return {
		name: "Azure Translator Code",
		short_name: "Azure Translator",
		description: "Generated by Azure Translator Code",
		start_url: "/",
		display: "standalone",
		background_color: "white",
		lang: "en",
		dir: "ltr",
		categories: ["utilities", "translator", "code"],
	};
}
